### ISSUE TITLE
NuGet restore failing on .NET 5

### ISSUE THREAD

**Issue by schmidtjohannes** [nosinovacao/dotnet-sonar#19]
Hi,

did you face this problem: https://github.com/NuGet/Announcements/issues/49 ?

I see your base image is the debian image of the sdk the certs are updated: https://github.com/nosinovacao/dotnet-sonar/blob/master/Dockerfile#L21

Probably a rebuild of the image will fix the problem, any chance to re-trigger it?

Thanks in advance

**Comment by gafda** [comment]
Hey there!

Thank you for your heads-up. Our most recent image with dotNet5 support was with the tag `20.12.2` containing the dotnet sdk 5.0.101 instead of the reported problematic dotnet sdk 5.0.102.
But this way we also bumped a minor version in the images for dotNetCore 3.1 and dotNet5.

Please take a look at our newest image tags.

Thank you for your collaboration!
