### ISSUE TITLE
Is it possible to build .net 4 ?

### ISSUE THREAD

**Issue by dennys** [nosinovacao/dotnet-sonar#28]
I have a .net 4.6 project and use a VM to build and do SonarQube scan.
But I want to find a docker solution to replace the VM, I can use this image to call SonarQube now,
but it's obvious I cannot build my project because this image only supports .NET 5/6/7.

I'm not sure, is it possible to build .net 4 in this image?

**Comment by gafda** [comment]
The building tools embedded in our image are only for the latest dotNetCore frameworks but SonarQube's SonarScanner for .NET tool should be 100% compatible with your solution since their tool is compatible with dotNetCore 2.1+ and .Net 4.6+.
Check the official website to know how to setup tooling for your use case:
https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scanners/sonarscanner-for-dotnet/
