### ISSUE TITLE
Java installation removal

### ISSUE THREAD

**Issue by rwyr** [nosinovacao/dotnet-sonar#33]
Hi, what is the reason of removing Java installation? It seems it is still required by the scanner. This is what I'm getting in my pipeline:

```
$ dotnet /sonar-scanner/SonarScanner.MSBuild.dll end /d:sonar.login="${SONAR_TOKEN}"
SonarScanner for MSBuild 7.1.1
Using the .NET Core version of the Scanner for MSBuild
Post-processing started.
Calling the SonarScanner CLI...
Could not find 'java' executable in JAVA_HOME or PATH.
The SonarScanner did not complete successfully
14:23:44.255  Post-processing failed. Exit code: 1
```

Can this error be avoided without adding Java back? Thank you!

**Comment by jaimesantosferreira** [comment]
Hello!

We removed the Java installation because, according to the official docs, from SonarScanenr 7.0.0 on, it is no longer needed. You can check it here: https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/7.0.0.95646.

Anyway, next week we can build an image with the new versions of .NET and SonarScanner, including the Java installation. In the meantime, feel free to use any of our earlier releases, since all those have it.

Thank you. Best regards,
Jaime

**Comment by jaimesantosferreira** [comment]
Hello, again.

We have just published new images, including the Java installation.

All the best,
Jaime
